version: '3.8'

services:
  stormlit-app:
    container_name: stormlit-app
    build: 
      context: ./app
    env_file:
      - ./app/.env
    environment:
      - PGHOST=stormlit-postgis
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=postgis
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace:cached
      - ./app:/app
    networks:
      - stormlit-network

  stormlit-postgis:
    container_name: stormlit-postgis
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    volumes:
      - stormlit-postgis-data:/var/lib/postgresql/data
    networks:
      - stormlit-network

  stormlit-pgadmin:
      container_name: stormlit-pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "55050:80"
      networks:
        - stormlit-network
      depends_on:
        - stormlit-postgis

networks:
  stormlit-network:
    name: stormlit-network

volumes:
  stormlit-postgis-data:
    name: stormlit-postgis-data