version: '3.8'

services:
  stormlit-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      - PGHOST=stormlit-postgis
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=postgis
    volumes:
      - .:/workspace:cached