version: '3.8'

services:
  stormlit-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      - PGHOST=stormlit-postgis
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=postgis
      - PGSTAC_ADMIN_PASSWORD=password
      - PGSTAC_INGEST_PASSWORD=password
      - PGSTAC_READ_PASSWORD=password
    volumes:
      - .:/workspace:cached