name: Build and Push Streamlit App

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2 # Must match region in config.py

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]
          then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::894169284666:role/Stormlit-Deployment-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build -t $ECR_REGISTRY/stormlit-development-streamlit:$IMAGE_TAG .
          docker push $ECR_REGISTRY/stormlit-development-streamlit:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/stormlit-development-streamlit:$IMAGE_TAG"

      - name: Set output
        id: vars
        run: echo "tag=${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT