name: Docker Build

on:
  workflow_call:
    inputs:
      push_to_registry:
        type: boolean
        default: false
        required: false
      platforms:
        type: string
        default: 'linux/amd64,linux/arm64'
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-streamlit-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: inputs.push_to_registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # tag events
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            # branch events - dev branch gets dev tag
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            # main branch gets latest tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./app
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push_to_registry }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-scout:
    needs: build-streamlit-image
    if: always()
    permissions:
      contents: read
    uses: ./.github/workflows/docker-scout.yml
    with:
      image_tag: ${{ needs.build-streamlit-image.outputs.image_tag || 'ghcr.io/fema-ffrd/stormlit:latest' }}
    secrets: inherit
