name: PR Checks
on:
  pull_request:
    branches: [main, dev]

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  sonarqube:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: ./.github/workflows/sonarqube.yml

  synth:
    permissions:
      contents: read
    uses: ./.github/workflows/synth.yml

  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      push_to_registry: true
      platforms: 'linux/amd64'
    secrets: inherit

  docker-scout:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/docker-scout.yml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit