name: Synth Terraform

on:
  pull_request:
    branches: [ main, ci-cd-init ]
  push:
    branches: [ main, ci-cd-init ]

jobs:
  synth-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./iac
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Synth with CDKTF
        working-directory: ./iac
        run: |
          pipenv run cdktf synth