name: Lint and Test

on:
  workflow_call:

jobs:
  iac-lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pipenv'
          
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          
      - name: Install dependencies
        run: pipenv install -d
          
      - name: Run Ruff Check
        run: pipenv run ruff check
        
      - name: Run Ruff Format
        run: pipenv run ruff format --check
        
      - name: Run Tests
        run: pipenv run pytest main-test.py

  streamlit-lint-and-test:
    runs-on: ubuntu-latest
    environment: ci
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: app/env.yml
          cache-environment-key: environment-dev
          cache-downloads-key: downloads-dev
          environment-name: ci
          
      - name: Run Ruff Check
        shell: bash -el {0}
        run: ruff check
        
      - name: Run Ruff Format
        shell: bash -el {0}
        run: ruff format --check
        
      - name: Run Tests
        shell: bash -el {0}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION}}
        run: pytest -m "not integration_postgres"
