name: Hello World
on:
  push:
    branches: [ ci-cd-init ]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-stormlit-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"